services:
  db:
    image: postgres:15
    container_name: arbitrage_db
    environment:
      POSTGRES_USER: hayk
      POSTGRES_PASSWORD: password
      POSTGRES_DB: askhayk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: askhayk
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
